apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- name: kube-state-metrics
  namespace: kube-system
  repo: https://prometheus-community.github.io/helm-charts
  version: 5.16.0
  releaseName: ksm
  includeCRDs: true
  valuesFile: ksm-values.yaml
